import type { AssertIQReport } from "../types.js";

export function renderDashboard(report: AssertIQReport): string {
  const data = JSON.stringify({
    summary: report.summary,
    dimensions: report.dimensions,
    history: report.history ?? []
  }).replace(/</g, "\\u003c");
  const issueCounts = report.issues.reduce<Record<string, number>>((counts, issue) => {
    counts[issue.ruleId] = (counts[issue.ruleId] ?? 0) + 1;
    return counts;
  }, {});
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>AssertIQ dashboard - ${escapeHtml(report.project)}</title>
<style>body{margin:0;background:#0a0c14;color:#e4e8f4;font:15px system-ui,sans-serif}.wrap{max-width:1100px;margin:auto;padding:32px 20px 60px}.muted{color:#8791a6}.hero{display:flex;justify-content:space-between;gap:20px;align-items:end;border-bottom:1px solid #252830;padding-bottom:24px}.score{font-size:56px;font-weight:900;color:#a78bfa}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:24px 0}.card,.issue{background:#13151b;border:1px solid #252830;border-radius:8px;padding:16px}.bar{height:8px;background:#252830;border-radius:8px;margin-top:10px}.fill{height:100%;background:linear-gradient(90deg,#4f8ef7,#a78bfa)}.section{margin-top:30px}.issue{margin:10px 0;border-left:4px solid #f7c948}.issue.high{border-left-color:#f76f6f}.tag{font:12px monospace;color:#a78bfa}.chart{width:100%;height:210px;background:#13151b;border:1px solid #252830;border-radius:8px}.legend{display:flex;flex-wrap:wrap;gap:12px;margin:8px 0}.legend span{font-size:12px}.dot{display:inline-block;width:8px;height:8px;border-radius:50%;margin-right:4px}@media(max-width:700px){.hero{display:block}.grid{grid-template-columns:1fr}}</style></head><body><main class="wrap"><section class="hero"><div><div class="muted">ASSERTIQ QUALITY DASHBOARD</div><h1>${escapeHtml(report.project)}</h1><p class="muted">${report.summary.tests} tests across ${report.summary.testFiles} files</p></div><div><div class="score">${escapeHtml(report.summary.grade)}</div><div class="muted">${report.summary.score}/100</div></div></section>
<section class="section"><h2>Score trend</h2><canvas id="overall" class="chart" aria-label="Overall score trend"></canvas></section><section class="section"><h2>Dimension trends</h2><div id="dimension-legend" class="legend"></div><canvas id="dimensions" class="chart" aria-label="Dimension score trends"></canvas></section><section class="grid">${report.dimensions.map((d) => `<article class="card"><div class="muted">${escapeHtml(d.name)}</div><h2>${escapeHtml(d.grade)} <small>${d.score}/100</small></h2><div class="bar"><div class="fill" style="width:${d.score}%"></div></div><div class="muted">${d.issueCount} risk(s)</div></article>`).join("")}</section>
<section class="section"><h2>Latest risks</h2>${report.issues.length ? report.issues.map((issue) => `<article class="issue ${issue.severity}"><div class="row"><strong>${escapeHtml(issue.message)}</strong><span class="tag">${escapeHtml(issue.ruleId)}</span></div><div class="muted">${escapeHtml(issue.file)}:${issue.line}${issue.testName ? ` - ${escapeHtml(issue.testName)}` : ""}</div><p>${escapeHtml(issue.remediation ?? "Review this finding and improve the test.")}</p></article>`).join("") : `<p class="muted">No risks detected.</p>`}</section>
<section class="section"><h2>Rule-count trends</h2><div id="rule-legend" class="legend"></div><canvas id="rules" class="chart" aria-label="Historical issue-count trends by rule"></canvas><p id="rule-empty" class="muted"></p></section>${report.warnings.length ? `<section class="section"><h2>Warnings</h2><pre>${escapeHtml(report.warnings.join("\n"))}</pre></section>` : ""}</main><script>const data=${data};const colors=['#4f8ef7','#a78bfa','#5ee8a0','#f7c948','#f76f6f','#7bc4ff'];function points(values,max){return values.map((v,i)=>[i,Math.max(0,Number(v)||0)]).map(([i,v])=>[i,v/max])}function draw(id,series,max){const c=document.getElementById(id),ctx=c.getContext('2d'),dpr=devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;c.width=w*dpr;c.height=h*dpr;ctx.scale(dpr,dpr);ctx.strokeStyle='#252830';ctx.beginPath();ctx.moveTo(12,h-18);ctx.lineTo(w-12,h-18);ctx.stroke();series.forEach((s,index)=>{const values=points(s.values,max);if(!values.length)return;ctx.strokeStyle=colors[index%colors.length];ctx.lineWidth=2;ctx.beginPath();values.forEach(([i,v])=>{const x=12+i*(w-24)/Math.max(1,values.length-1),y=h-18-v*(h-36);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()})}function legend(id,series){const root=document.getElementById(id);series.forEach((s,index)=>{const item=document.createElement('span'),dot=document.createElement('i');dot.className='dot';dot.style.background=colors[index%colors.length];item.append(dot,document.createTextNode(s.name));root.append(item)})}const snapshots=data.history.concat([{score:data.summary.score,dimensions:data.dimensions,ruleCounts:${JSON.stringify(issueCounts).replace(/</g, "\\u003c")}}]);draw('overall',[{name:'Overall',values:snapshots.map(s=>s.score)}],100);const dimensions=data.dimensions.map(d=>({name:d.name,values:snapshots.map(s=>{const found=(s.dimensions||[]).find(x=>x.id===d.id);return found?found.score:d.score})}));legend('dimension-legend',dimensions);draw('dimensions',dimensions,100);const totals={};snapshots.forEach(s=>Object.entries(s.ruleCounts||{}).forEach(([key,value])=>{if(typeof value==='number')totals[key]=(totals[key]||0)+value}));const rules=Object.keys(totals).sort((a,b)=>totals[b]-totals[a]).slice(0,5).map(key=>({name:key,values:snapshots.map(s=>typeof(s.ruleCounts||{})[key]==='number'?(s.ruleCounts||{})[key]:0)}));if(rules.length){legend('rule-legend',rules);draw('rules',rules,Math.max(1,...rules.flatMap(r=>r.values)))}else document.getElementById('rule-empty').textContent='No rule-count history yet.';</script></body></html>`;
}

function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char] ?? char);
}
